language: c
dist: trusty
sudo: required
env:
    global:
        - DOCKER_VERSION=17.11.0~ce-0~ubuntu
        - DOCKER_EXPERIMENTAL=true
        - MAKEFLAGS="--jobs=2 --max-load=4 --always-make --no-print-directory"
    matrix:
        - >-
            IMAGE_NAME=php PHP_VERSION=7.1.12
            PHP_SHA256=a0118850774571b1f2d4e30b4fe7a4b958ca66f07d07d65ebdc789c54ba6eeb3
            GPG_KEY_LIST="A917B1ECDA84AEC2B568FED6F50ABC807BD5DCD0
            528995BFEDFBA7191D46839EF9BA0ADA31CBD89E"
        - >-
            IMAGE_NAME=php PHP_VERSION=7.2.0RC6 LATEST_TAG=next
            PHP_SHA256=be4df00ff5b66e9f13c83e1d08d1d5384ae7ccc820e26f7e5f9e660011496a9e
            GPG_KEY_LIST="1729F83938DA44E27BA0F4D3DBDB397470D12172
            B1B44D8F021E4E2D6021E995DC9FF8D3EE5AF27F"
            PHP_URL='http://downloads.php.net/~pollita/php-${PHP_VERSION}.tar.xz'
            PHP_ASC_URL='http://downloads.php.net/~pollita/php-${PHP_VERSION}.tar.xz.asc'
        - IMAGE_NAME=netutils
        - IMAGE_NAME=flow FLOW_VERSION=0.59.0 OCAML_VERSION=4.03.0
        - IMAGE_NAME=rabbitmq RABBITMQ_VERSION=3.6.12
before_install:
    - >
        if [ ! -z "${DOCKER_EXPERIMENTAL}" ] ; then
            echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
        fi

        if [ "$(docker version -f '{{.Server.Version}}')|sed -e 's/-ce.*$//'" !=
        "$(echo ${DOCKER_VERSION}|sed -e 's/~ce.*$//')" ] ; then
            apt-cache madison docker-ce
            sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-ce=${DOCKER_VERSION}
        else
            sudo service docker restart
        fi
install:
    - 'make -C ${IMAGE_NAME} pull'
script:
    - 'make -C ${IMAGE_NAME} build'
    - 'make -C ${IMAGE_NAME} test'
after_success:
    - 'make -C ${IMAGE_NAME} tag'
    - docker image ls
deploy:
    provider: script
    script: >-
        docker login --username="${DOCKER_HUB_USERNAME}"
        --password="${DOCKER_HUB_PASSWORD}" && make -C ${IMAGE_NAME} push
    skip_cleanup: true
    'on':
        branch: master
notifications:
    slack:
        secure: "bpjwkWe2bGp2n6UEid2uI52lBeD7FgjM91E+0xss5xh+/YASqnh2JSQ7lby1K+KQdXwpH8mGX/p1Z6q3v/WvkfPbrGIVB3OVI9sfUB0eqpSky1ca2x3cGlZl7C4irX6Q8svrEsu2hp64ULctwSMwwiJCgf97w/u2Bzje8SgBzI4jbdEcL0kmMer639LWdQqnd9zX4HGuuoKUyL0zU6VYGtwiGSDg4k+GW7M34v3J3JgOu/X2RMQ+axWVwjRhLSLkkQCBxDqKXLvkwlHv3JDrdXPZtcOX2ytjty1lg8bDjETk8npJQ+7SQzS5VTaM7y16L1004Jld0VS8vEDQO/5k8DuwUFWWafXWiQKvp/O8RfUIjA2eDwJBTL/OfFfI2RF2HHD9OAWDGt3Cqx9mgO/AdWrYN2iPQ/E51Dg0hkjdGP4RXZRbBC1TaT2WitDzdNZIsWr8wNviu+SVbwbfrqgkA7QOpFQTpxyV6JqFb4gnjmifp/1O/tnrNj/Vcl0j/uxC9NeZDY6HuuUGgY2rBWJ4mSf7agBdMwg7IhVX998qIB0LBUfsxmCjC3WFTkkeKafcIMZcUPK/pWwG+RddKmjWEJaR30j5Tm3OEAE89i4d9sZN7olIh7+8M4tt7BSQscUEYz419K3zXesE3oLf67Tea4uqVq61koZrgaBhoPI40SI="
    email:
        recipients:
            - ci@ubirak.org
        on_success: change
        on_failure: change
