language: c
dist: trusty
sudo: required
env:
    global:
        - DOCKER_VERSION=17.06.2~ce-0~ubuntu
        - DOCKER_EXPERIMENTAL=true
        - MAKEFLAGS="--jobs=2 --max-load=4 --always-make --no-print-directory"
    matrix:
        - >-
            IMAGE_NAME=php PHP_VERSION=7.1.11
            PHP_SHA256=074093e9d7d21afedc5106904218a80a47b854abe368d2728ed22184c884893e
            GPG_KEY_LIST="A917B1ECDA84AEC2B568FED6F50ABC807BD5DCD0
            528995BFEDFBA7191D46839EF9BA0ADA31CBD89E"
        - >-
            IMAGE_NAME=php PHP_VERSION=7.2.0RC5 LATEST_TAG=next
            PHP_SHA256=92a745048912beb3f6c2a3c188ce695a51852c67201fdf9a21dafe59f51aecc1
            GPG_KEY_LIST="1729F83938DA44E27BA0F4D3DBDB397470D12172
            B1B44D8F021E4E2D6021E995DC9FF8D3EE5AF27F"
            PHP_URL='http://downloads.php.net/~pollita/php-${PHP_VERSION}.tar.xz'
            PHP_ASC_URL='http://downloads.php.net/~pollita/php-${PHP_VERSION}.tar.xz.asc'
        - IMAGE_NAME=netutils
        - IMAGE_NAME=flow FLOW_VERSION=0.57.3 OCAML_VERSION=4.03.0
        - IMAGE_NAME=rabbitmq RABBITMQ_VERSION=3.6.12
before_install:
    - >
        if [ ! -z "${DOCKER_EXPERIMENTAL}" ] ; then
            echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
        fi

        if [ "$(docker version -f '{{.Server.Version}}')|sed -e 's/-ce.*$//'" !=
        "$(echo ${DOCKER_VERSION}|sed -e 's/~ce.*$//')" ] ; then
            apt-cache madison docker-ce
            sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-ce=${DOCKER_VERSION}
        else
            sudo service docker restart
        fi
install:
    - 'make -C ${IMAGE_NAME} pull'
script:
    - 'make -C ${IMAGE_NAME} build'
    - 'make -C ${IMAGE_NAME} test'
after_success:
    - 'make -C ${IMAGE_NAME} tag'
    - docker image ls
deploy:
    provider: script
    script: >-
        docker login --username="${DOCKER_HUB_USERNAME}"
        --password="${DOCKER_HUB_PASSWORD}" && make -C ${IMAGE_NAME} push
    skip_cleanup: true
    'on':
        branch: master
notifications:
    slack: 'verylastroom:yqs3UqNXq6H3L9p8npeVFWgh'
    email:
        recipients:
            - ci@karibbu.com
        on_success: change
        on_failure: change
